label variable subjects "zTree: Table (completely irrelevant)"
label variable other1 "Endowment of other groupmember 1"
label variable other2 "zTree"
label variable distribution "distribution of endowment for current period"
label variable fullinfo "zTree"
label variable g "zTree"
label variable ballot "random number for procedure selection"
label variable draw "zTree: for procedure selection"
label variable chosenone "zTree: for procedure selection"
label variable groupdecisionredistribution "final decision of procedure"
label variable groupdecisionredistribution "final decision about redistribution"
label variable netinc "net income"
label variable pay "equals net income"
label variable lotterypayoff "lottery for random selection of period to pay"
label variable client "computer in lab"
label variable sem "Semester"

label variable dem_1 "Bei politischen Entscheidungen sollte immer das Gemeinwohl und nicht das eigene Interesse im Vordergrund stehen"
label variable dem_2 "Es ist in der Demokratie wichtig zu verstehen, aus welchen Gründen andere Menschen andere Meinungen haben"
label variable dem_3 "Demokratisch getroffene Entscheidungen muss man auf jeden Fall akzeptieren, auch wenn sie den eigenen Interessen widersprechen."
label variable dem_4 "Wenn sich für eine Entscheidung eine große Mehrheit findet, spricht das dafür, dass die Entscheidung richtig ist."
label variable dem_5 "Was ist für Sie im Zweifelsfall wichtiger?"

label variable sterben "Die Zulässigkeit von Sterbehilfe"
label variable zuwandern "Die Steuerung der Zuwanderung"
label variable steuer "Steuergerichtigkeit"
label variable gruenenergie "Die Förderung erneuerbarer Energien"

label variable self_sterben "Eigene Meinung: Die Zulässigkeit von Sterbehilfe"
label variable self_zuwandern "Eigene Meinung: Die Steuerung der Zuwanderung"
label variable self_steuer "Eigene Meinung: Steuergerichtigkeit"
label variable self_grueneenergie "Eigene Meinung: Die Förderung erneuerbarer Energien"

label variable mehrheit_sterben "Deutschland: Die Zulässigkeit von Sterbehilfe"
label variable mehrheit_zuwandern "Deutschland: Die Steuerung der Zuwanderung"
label variable mehrheit_steuer "Deutschland: Steuergerichtigkeit"
label variable mehrheit_grueneenergie "Deutschland: Die Förderung erneuerbarer Energien"

label variable gefallen "Wenn mir jemand einen Gefallen tut, bin ich bereit dies zu erwidern." 
label variable rache "Wenn mir schweres Unrecht zuteil wird, werde ich mich um jeden Preis bei der nächsten Gelegenheit dafür rächen."
label variable lage "Wenn mich jemand in eine schwierige Lage bringt, werde ich das Gleiche mit ihm machen."
label variable helfen "Ich strenge mich besonders an, um jemandem zu helfen, der mir früher schon mal geholfen hat."
label variable beleidigt "Wenn mich jemand beleidigt hat, werde ich mich ihm gegenüber auch beleidigend verhalten."
label variable kosten "Ich bin bereit Kosten auf mich zu nehmen, um jemandem zu helfen, der mir früher einmal geholfen hat."

label variable risk_base "Risikobereitschaft"
label variable risk2 "bei Geldanlagen?"
label variable risk3 "bei Freizeit und Sport?"
label variable risk4 "bei Ihrer beruflichen Karriere?"
label variable risk5 "bei Ihrer Gesundheit?"
label variable risk6 "beim Vertrauen in fremde Menschen?"
label variable risk1 "beim Autofahren" 

label variable pol_selbstein "Links-Rechts selbsteinstufung" 
